baseURL = 'http://bostian.io/'
languageCode = 'en-us'
title = 'Philip Bostian'
theme = 'typo'

# publishing directory
publishDir = "docs"

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "The technical blog and website of Philip Bostian"

# Appearance settings
theme = 'dark'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hello there!'
homeIntroContent = """
I design and develop AI products and have a passion for innovation in the life sciences.

Read more [about me](/b.io) or check out my [posts](/posts), [projects](/projects), or [public vault](https://publish.obsidian.md/b-io/Home+%E2%97%8A).
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
# [[params.social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/user/"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@user"

[[params.social]]
name = "github"
url = "https://github.com/bostian-io"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "vault"
url = "https://publish.obsidian.md/b-io/Home+%E2%97%8A"
rel = "noopener noreferrer"
target = "_blank"

[[params.menu]]
name = "b.io"
url = "/b.io"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = true
repo = "bostian-io/b.io"
repoid = "R_kgDOMfV_zQ"
category = "bostian.io comments"
categoryid = "DIC_kwDOMfV_zc4ChbLJ"
mapping = "pathname"
theme = "preferred_color_scheme"

# Module
[module]
[module.hugoVersion]
extended = false
min = "0.116.0"